# Generated by Django 5.1 on 2024-09-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=20, verbose_name="Автор")),
                (
                    "title_book",
                    models.CharField(max_length=70, verbose_name="Название книги"),
                ),
                (
                    "chapter",
                    models.CharField(max_length=70, verbose_name="Название главы"),
                ),
                ("full_text", models.TextField(verbose_name="Текст главы")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
        ),
    ]
