# Generated by Django 5.1 on 2024-11-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_books_style_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="books",
            options={"verbose_name": "Книга", "verbose_name_plural": "Книги"},
        ),
    ]
