# Generated by Django 5.1 on 2024-12-02 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_books_options"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_book",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название книги"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(max_length=70, verbose_name="Название главы"),
                ),
                ("full_text", models.TextField(verbose_name="Текст главы")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
            options={
                "verbose_name": "Глава",
                "verbose_name_plural": "Главы",
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style_book",
                    models.CharField(
                        default="Не указано", max_length=20, verbose_name="Жанр"
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.DeleteModel(
            name="Books",
        ),
        migrations.AddField(
            model_name="book",
            name="style_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="books.style"
            ),
        ),
    ]
