# Generated by Django 5.1 on 2024-08-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=20, verbose_name="Автор")),
                ("titles", models.CharField(max_length=70, verbose_name="Название")),
                ("anons", models.CharField(max_length=250, verbose_name="Анонс")),
                ("full_text", models.TextField(verbose_name="Статья")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
        ),
    ]
