# Generated by Django 5.1 on 2024-08-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
    ]
