# Generated by Django 5.1 on 2024-09-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_articles_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articles",
            old_name="titles",
            new_name="title",
        ),
    ]
