# Generated by Django 5.1 on 2024-12-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_rename_titles_articles_title"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_article",
                    models.CharField(max_length=70, verbose_name="Название"),
                ),
                (
                    "anons_article",
                    models.CharField(max_length=250, verbose_name="Анонс"),
                ),
                ("full_text_art", models.TextField(verbose_name="Статья")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.DeleteModel(
            name="Articles",
        ),
    ]
